### ISSUE TITLE
No Images shown

### ISSUE THREAD

**Issue by mats68** [dubvfan87/meteor-emoticons#3]
Hi, Somehow it's not working here: 
`{{parseEmoticons ":D"}}`

gives as output on page:
`<img class="meteoremoticon" src="/packages/mattimo_emoticons/assets/images/emoticons/caritas_05.png">`

**Comment by mmoyles87** [comment]
Try using {{{parseEmoticons ":D"}}} with 3 {'s. I think that's the problem, sorry I will update the docs.

**Comment by mats68** [comment]
Thanks that works!

**Comment by dezudas** [comment]
that works thank you, there are some differences in doc please update 
there are still {{ in [ https://atmospherejs.com/mattimo/emoticons](url)
