### ISSUE TITLE
Add CSS class to images

### ISSUE THREAD

**Issue by dnish** [dubvfan87/meteor-emoticons#4]
Hey,
it would be great if you could add a CSS class to the smiley images, so it would be easier to identify and style them via CSS (f.e. max-height etc.).

**Comment by mmoyles87** [comment]
Currently they have css="meteoremoticon" on all of the img tags. I will add it to the readme

**Comment by dnish** [comment]
Uhh sorry, didn't see that. I'm using "striptags" and it filtered the class attribute. Now it's working, thanks.
