### ISSUE TITLE
sanitizer html

### ISSUE THREAD

**Issue by mats68** [dubvfan87/meteor-emoticons#5]
Hello,
Is it neccessary to add html sanitizer ? For example this here:
https://atmospherejs.com/vazco/universe-html-purifier

Thanks

**Comment by mmoyles87** [comment]
That's a good idea. I think I will add a 2nd helper that is sanitized so it's optional and the package isn't overstepping it's bounds.

**Comment by JesusBusquets** [comment]
Tried to use from atmospherejs.com  , It did't work until I realized that the helper info here is wrong:
Says {{parseEmoticons "text"}}
but on github says:     {{{parseEmoticons "text"}}}   and this works.
