### ISSUE TITLE
how to access parseEmoticons method in .js file?

### ISSUE THREAD

**Issue by vijaychoudhary24** [dubvfan87/meteor-emoticons#8]
As I have gone through the package documentation, it has given us a way to parse my text inside view html file. to be use like this
`{{parseEmoticons "text"}}`

but I have a scenario where I wanted to use above method in js file.
like below:
`parseEmoticons(text);`

how could I access this package in my UI helper js file, which return me the filtered message text.

**Comment by mmoyles87** [comment]
It's a global helper so you can call it like any other:

`var result = Blaze._globalHelpers.parseEmoticons(text);`

**Comment by vijaychoudhary24** [comment]
Thank you very much :+1: 
You have save my day, it works like charm.
